service: pocketsphinx
deepspeech:
    model_dir: deepspeech/models
pocketsphinx:
    model_dir: pocketsphinx/model
azure:
    api_subkey:
amazon:
    secret_key_id:
    secret_access_key:
    region:
    s3_bucket:
